### ISSUE TITLE
Converting a line of text into a list item breaks the text after the first word

### ISSUE THREAD

**Issue by alex-ju** [github/markdown-toolbar-element#1]
### Context
Converting a line of text into a list item

### Process
Place the cursor at the beginning of a line. Press the "Add a bulleted list" button in the toolbar.

### Current result
When converting a line of text into a list:
- adds the `- ` in front of the current line
- breaks the line after the first word

### Expected result
- adds the `- ` in front of the current line and doesn't introduce new lines

### Example
![kapture 2018-08-22 at 13 18 24](https://user-images.githubusercontent.com/788096/44463271-1ca38980-a60f-11e8-8d0b-0db015ff2917.gif)

### Possible Fix
I'm planning to look into this and raise a pull request, but I was wondering if there is a reason for having the current behaviour.

**Comment by muan** [comment]
This is fixed in `1.0.1`! Apologies for the delay. Thanks for the report.
