### ISSUE TITLE
`class` expressions in dist bundles

### ISSUE THREAD

**Issue by th0r** [github/markdown-toolbar-element#11]
v1.0.3 contains `class` expressions in both `umd` and `esm` dist bundles.
It doesn't allow to use this module in IE11 with custom elements polyfill, but I was supported before (in v0.1.1).

**Comment by muan** [comment]
IE11 support was dropped in [`v0.2.0`](https://github.com/github/markdown-toolbar-element/releases/tag/v0.2.0) via #7. Consider using https://github.com/github/babel-plugin-transform-custom-element-classes to transform them on the app side.
