### ISSUE TITLE
It is possible to add more markdown buttons?

### ISSUE THREAD

**Issue by nico93f** [github/markdown-toolbar-element#35]
Lets say i want to add a `Title 1`, `Title 2` and `Title 3` buttons, that sets the `#`, `##` and `###` respectively.

It is possible to add custom buttons with custom prefixes a suffixes?

**Comment by koddsson** [comment]
The `<md-header>` element has a `level` attribute that denotes the title level. 

https://github.com/github/markdown-toolbar-element/blob/7bbdf32ab7f7343e6ba10d6f30320aaf0d8c7709/src/index.ts#L109-L123

So you can implement those buttons like this

```html
<md-header level="1">Title 1</md-header>
<md-header level="2">Title 2</md-header>
<md-header level="3">Title 3</md-header>
```

**Comment by mirandarfsm** [comment]
Hi @koddsson! 
Is there a possibility extend project to add news features like table, task list, horizontal rule...?
I'm grateful.

**Comment by koddsson** [comment]
> Hi @koddsson!
> Is there a possibility extend project to add news features like table, task list, horizontal rule...?
> I'm grateful.

Yes, you can write a component that implements the functionality you want. You can look at the other markdown buttons in the project for prior art.

**Comment by Parziphal** [comment]
Hello.
It's not possible to extend from the functionality the toolbar comes with, correct? I wanted to create a new button by extending from the base `MarkdownButtonElement` class, but it's not exported. And even if I access it from the other buttons' prototype, I can't access the `styles` variable.

**Comment by dkretsch12** [comment]
Similarly to @Parziphal I am unsure how to implement custom buttons with custom functionality. Access to the `styles` variable would be very helpful

**Comment by iKrishnaSahu** [comment]
I was trying to create a custom component but as `styles` var is not available globally, unable to implement it.
Need a way to access `styles`

**Comment by Parziphal** [comment]
I ended up copying the source code as part of my code and made minimum necessary exports so it can be configurable. Not ideal, but it was either that or stay road blocked.
