### ISSUE TITLE
Doesn't Work With Angular Universal

### ISSUE THREAD

**Issue by jdgamble555** [github/markdown-toolbar-element#65]
The core code seems to reference the window object directly, which as we know is bad code.  This can't be used with Angular Universal as is.

**Comment by koddsson** [comment]
We don't align components like this to any specific frameworks so I'm gonna close this as a won't fix. Looks like there's a issue open on the Angular Universal issue tracker for Custom Element support.

https://github.com/angular/universal/issues/1599
