### ISSUE TITLE
C/C++ syntax highlighting broken after macro definition in compare, pull requests and markdown on GitHub

### ISSUE THREAD

**Issue by anitahammer** [github/markdown-toolbar-element#82]
I don't know where to file that bug, tried my best to find the place.

```cpp
#define hashmap_t khash_t(str)
bool hashMapContainsItem();
```

See https://github.com/microsoft/vscode-cpptools/issues/562

**Comment by keithamus** [comment]
Thanks for the issue, this is the wrong venue for this. Please file a support ticket with GitHub: https://docs.github.com/en/support/contacting-github-support
